using System.Reflection;

namespace Hive.Server.Common.Application;


public class ChannelHandlerBinderAttribute : Attribute
{
    public ChannelHandlerBinderAttribute(Type type)
    {
        Type = type;
    }

    public Type Type { get; }
}
public static class MessageHandlerBinderProvider
{
    private static readonly Dictionary<Type,IMessageHandlerBinder> BinderCache;
    static MessageHandlerBinderProvider()
    {
        BinderCache = new Dictionary<Type, IMessageHandlerBinder>();
        var assemblies = AppDomain.CurrentDomain.GetAssemblies();
        foreach (var assembly in assemblies)
        {
            foreach (var type in assembly.GetTypes())
            {
                var attribute = type.GetCustomAttribute<ChannelHandlerBinderAttribute>();
                if (attribute != null)
                {
                    if (Activator.CreateInstance(type) is IMessageHandlerBinder binder)
                    {
                        BinderCache.Add(attribute.Type,binder);
                    }
                }
            }
        }
    }
    public static IMessageHandlerBinder GetHandlerBinder(Type type)
    {
        lock (BinderCache)
        {
            if (BinderCache.TryGetValue(type, out var binder))
            {
                return binder;
            }
            throw new InvalidOperationException($"No binder found for type {type}, It should be generated by code generator.");
        }
    }
}