<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>10</LangVersion>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="LoadBalancers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="System.IO.Pipelines" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hive.Codec.Shared\Hive.Codec.Shared.csproj" />
    <ProjectReference Include="..\Hive.Network.Abstractions\Hive.Network.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

</Project>
